spring:
  application:
    name: cream-commerce

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_local_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging:
  level:
    # JDBC 초기화 로그
    org.springframework.test.context.jdbc: DEBUG
    # Hibernate SQL 로그
    org.hibernate.SQL: DEBUG